# Generated by Django 3.0 on 2023-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contant',
        ),
    ]
