# Generated by Django 3.0 on 2023-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articale', '0002_remove_article_contant'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contant',
            field=models.TextField(default=None),
        ),
    ]
