# Generated by Django 3.0 on 2023-05-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articale', '0007_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
