# Generated by Django 3.0 on 2023-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articale', '0008_auto_20230514_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
