# Generated by Django 3.0 on 2023-06-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articale', '0009_auto_20230514_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
    ]
