# Generated by Django 3.0 on 2023-07-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredieant',
            new_name='RecipeIngredieant',
        ),
    ]
