# Generated by Django 3.0 on 2023-07-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230704_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredieant',
            new_name='RecipeIngredient',
        ),
    ]
